config/routes.rb
Aozhen::Application.routes.draw do

  root :to => "home#index"
  resources :robots
  match 'command'     => 'robots#command'

end

app/models/robot.rb
class Robot < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/settings.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/robots_controller.rb
# -*- coding: utf-8 -*-
require 'builder'
require 'xmlsimple'
class RobotsController < ApplicationController

  def index
  #  @config = XmlSimple.xml_in(Settings.xml_path)   
    @config = File.open(Settings.xml_path).readlines()
  end

  def create
    write_file(create_xml("defalut",params))
    redirect_to :action => 'index'
  end
  

  def command        
    send_http_request(create_xml("command",params[:optionsRadios]))
    redirect_to :action => 'index'
  end


  private
  def write_file xml_data
    open(Settings.xml_path,'w') do |f|  
      f.puts xml_data  
    end  
  end

  def send_http_request command_xml
    EventMachine.run {
   #   http = EventMachine::HttpRequest.new('http://google.com/').post :body => {:string => [:value1, :value2]}
      http = EventMachine::HttpRequest.new(Settings.http_request_path).post :body => {:command => "mmand_xml"}
      http.errback { flash[:error]="响应请求失败！，命令没执行，从从新发送！" ; EM.stop }
      http.callback {
        flash[:success] ="响应请求成功，命令成功执行！"
        write_file http.response
        EventMachine.stop
      }
    }
  end


  def create_xml tyle,data
    xml = Builder::XmlMarkup.new( :indent => 2 )
    xml.instruct! :xml, :encoding => "UTF-8"    
    return xml.command {|d| d.value data} if tyle.eql? "command"
    xml.defalut_config do |d|      
      data.map {|k,_| d.send(k.to_sym,k)}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/home/index.html.slim
h1 初始化机器人坐标：
hr
form.form-horizontal action="#{robots_path}" method="post"
    
  .control-group
    label.control-label for="inputEmail" 棋盘长
    .controls
      input type="text" name="length"
  .control-group
    label.control-label for="inputEmail" 棋盘宽
    .controls
      input type="text" name="width"

  .control-group
    label.control-label for="inputEmail" 机器人x轴位置
    .controls
      input type="text" name="x"
  .control-group
    label.control-label for="inputEmail" 机器人y轴位置
    .controls
      input type="text" name="y"
  .control-group
    label.control-label for="inputEmail" 机器人所在方向
    .controls
      input type="text" name="d"
  .control-group
    .controls
      button type="submit" class="btn btn-primary" data-disable-with="处理中..." 确定

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aozhen</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/robots/index.html.slim
- unless flash[:success].blank?
  .alert.alert-info
    a.close data-dismiss="alert" ×
    strong 成功!&nbsp;
    span = flash[:success]
- unless flash[:error].blank?
  .alert.alert-error
    a.close data-dismiss="alert" ×
    strong 错误!&nbsp;
    span = flash[:error]

h1 目前机器人的坐标为：

p = @config

h1 向机器人发送指令：
hr
form.form-horizontal action="#{command_path}" method="post"
    
  .control-group
    label.control-label for="inputEmail"　输入你要发送的指令（可选）：
    .controls
      label class="radio"
        input type="radio" name="optionsRadios" id="optionsRadios2" value="option2" R
      label class="radio"
        input type="radio" name="optionsRadios" id="optionsRadios2" value="option2" L
      label class="radio"
        input type="radio" name="optionsRadios" id="optionsRadios2" value="option2" M
  .control-group
    .controls
      button type="submit" class="btn btn-primary" data-disable-with="处理中..." 确定